<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Serialize/Exception.php
 */

/**
 * An exception representative of a serialization problem
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Serialize_Exception extends RuntimeException
{
    protected $_thing;
    protected $_input;
    protected $_encoding;

    /**
     * @param string $errorMessage
     * @param int $errorNo
     * @param mixed|string $thingOrInput
     * @param boolean $encoding
     */
    public function __construct($errorMessage, $errorNo, $thingOrInput, $encoding)
    {
        parent::__construct($errorMessage, $errorNo);
        $this->_encoding = $encoding;
        if ($encoding) {
            $this->_thing = $thingOrInput;
        } else {
            $this->_input = $thingOrInput;
        }
    }

    /**
     * Did the exception occured while encoding an object
     *
     * @return boolean
     */
    public function isEncoding()
    {
        return $this->_encoding;
    }

    /**
     * Retrieves the object to be encoded
     *
     * @return mixed
     */
    public function getThing()
    {
        return $this->_thing;
    }

    /**
     * Retrieves the input to be decoded
     *
     * @return string
     */
    public function getInput()
    {
        return $this->_input;
    }
}
