<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/testimonial/style.css')?>" />
<style>
.mw_clear{clear:both;width:100%;}
</style>
<h3><?php echo Mage::helper('testimonial')->__('What our customers say'); ?></h3>
<div style="float:right; font-weight:bold; margin-bottom:0.4em;margin-right:0.4em;"><a href="<?php echo Mage::getUrl("testimonial/submit"); ?>"><?php echo Mage::helper('testimonial')->__('Submit Your Testimonial'); ?></a></div>
<div class="mw_clear"></div>
<?php 
	$testimonial = $this->getTestimonials();
	$allow_media = (Mage::getStoreConfig('hm_testimonial/general/allow_media')) ? Mage::getStoreConfig('hm_testimonial/general/allow_media'):0;
	$allow_datetime = Mage::getStoreConfig('hm_testimonial/general/allow_datetime');
?>
<?php
    if($testimonial->count() < 1):
?>
<div class="postWrapper">
<p><?php echo Mage::helper('testimonial')->__('No Testimonials'); ?></p>
</div>
<?php
    else:
?>
<div class="postWrapper">
<?php foreach ($testimonial as $post): ?>
	<?php if($allow_media){?>     
     <div style="border-bottom:1px solid silver;">
     	<div class="mw_clear" style="height:5px;"></div>
     	<div class="mw_testimonial_me">
     	<?php $mediaUpload = $post->getMedia();
     		$mediaURL = $post->getMediaUrl();
     		if ($mediaUpload)
     			$media = $this->getMediaUrl($mediaUpload);
     		elseif ($mediaURL)
     			$media = $mediaURL;
     		else 
     			$media = false;
     			
     		?>
     	<?php if ($media):?>
     		<?php $file_ext = array(); ?>
			<?php $file_ext = explode('.',$media); ?>
			<?php $file_ext = $file_ext[sizeof($file_ext)-1];?>
			<?php $file_ext = strtolower($file_ext) ?>
     		<?php if (strpos($media, 'www.youtube.com')!==false || $file_ext=='flv'|| $file_ext=='avi'|| $file_ext=='mp3' || $file_ext=='mp4' ):?>
     			<div id="mw_testimonial_<?php echo $post->getId(); ?>"></div>
     			<script type='text/javascript'>
					  jwplayer('mw_testimonial_<?php echo $post->getId(); ?>').setup({
					    'flashplayer': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'testimonial/player.swf';?>',
						'skin': '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'testimonial/glow.zip';?>',
					    'file': '<?php echo $media;?>',
						'stretching':'fill',
						'controlbar.position':'over',
					    'width': '<?php echo $this->getWidthMedia(); ?>',
					    'height': '<?php echo $this->getHeightMedia();?>'
					  });
				</script>
			<?php elseif ($file_ext=='swf'):?>
					<object classid="clsid:your-class-id" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0">
				 		<param name=movie value="">
				 		<param name="autoplay" value="false" />
				 		<param name="controller" value="true" />
				    	<param name=quality value=high>
				    	<param name="wmode" value="transparent">
				    	<embed src="<?php echo $media;?>" 
				    			quality="high" 
				    			wmode="transparent"
				    			width="<?php echo $this->getWidthMedia();?>"
				    			height="<?php echo $this->getHeightMedia();?>" 
				    			pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash"
				    			type="application/x-shockwave-flash">
				    	</embed> 
			    	</object>
			<?php else: ?>
					<img src="<?php echo $media;?>" width="<?php echo $this->getWidthMedia();?>" height="<?php echo $this->getHeightMedia();?>">
     		<?php endif;?>
     				
     	<?php endif; ?>
     	</div>
     	<div class="tes_info">
	    	<div style="font-style:italic;margin:0.4em 0.4em;"><?php echo $post->getDescription(); ?></div>
	     	<div class="mw_clear"></div>
			<div style="float:right;margin:0.4em 0.4em;"><?php echo $post->getClientName(); ?>
			<?php if($allow_datetime) echo '<br/><em>'.Mage::helper('core')->formatDate($post->getCreatedTime(),'medium',true).'</em>';?>
			<?php 
			
				$allow_Email = Mage::getStoreConfig('hm_testimonial/general/allow_email');
				$allow_address = Mage::getStoreConfig('hm_testimonial/general/allow_address');
				$allow_company = Mage::getStoreConfig('hm_testimonial/general/allow_company');
		                if($allow_Email && $post->getEmail()!=''){
				      echo ' - '.$post->getEmail();
				}
				if($allow_company && $post->getCompany()!='') {?>- <a href="<?php echo $post->getWebsite(); ?>" ><?php echo $post->getCompany();?></a><?php } 
				if($allow_address && $post->getAddress()!=''){
					echo ' - '.$post->getAddress();
				}
			?>
			</div>
			<div class="mw_clear"></div> 
		</div>
		<div class="mw_clear" style="height:4px;"></div>
    </div>
    <?php }else{?>
    	<div>
        	<blockquote style="font-style:italic; margin-right:0.4em; text-indent: 20px;margin: 0px;background:url('<?php echo $this->getSkinUrl('images/testimonial/icon_bt.gif');?>') no-repeat left top;"><?php echo $post->getDescription(); ?></blockquote>
			<p style="float:right; margin-right:0.4em; "><?php echo $post->getClientName(); ?>
			<?php if($allow_datetime) echo '<br/><em>'.Mage::helper('core')->formatDate($post->getCreatedTime(),'medium',true).'</em>';?>
			<?php 
			
				$allow_Email = Mage::getStoreConfig('hm_testimonial/general/allow_email');
				$allow_address = Mage::getStoreConfig('hm_testimonial/general/allow_address');
				$allow_company = Mage::getStoreConfig('hm_testimonial/general/allow_company');
		                if($allow_Email && $post->getEmail()!=''){
				      echo ' - '.$post->getEmail();
				}
				if($allow_company && $post->getCompany()!='') {?>- <a href="<?php echo $post->getWebsite(); ?>" ><?php echo $post->getCompany();?></a><?php } 
				if($allow_address && $post->getAddress()!=''){
					echo ' - '.$post->getAddress();
				}
			?>
			</p>
   		</div>
    	<div class="mw_clear"></div>  
   <?php }?> 
<?php endforeach; ?>
</div>
<?php
	echo $this->getToolbarHtml();
?> 
<?php
    endif;
?>