<?php
/**
 * Layered Navigation Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Nav
 * @version      2.5.4
 * @license:     yc4tx3fdyujjEs5czyndvhoc8zpLrKl3OCuGehtGvM
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
//<![CDATA[
function switchAttributeInputType()
{
    if($('frontend_input') && ($('frontend_input').value=='select' || $('frontend_input').value=='multiselect')){
        if($('is_filterable') && !$('is_filterable').getAttribute('readonly')){
            $('adjnav_block_type').disabled = false;
            $('adjnav_display_type').disabled = false;
        }
    }
    else if($('frontend_input') && $('frontend_input').value=='price') {
        $('adjnav_display_type').disabled = true;
    }
    else {
        $('adjnav_block_type').disabled = true;
        $('adjnav_display_type').disabled = true;
    }
}
switchAttributeInputType();

if($('frontend_input')){
    Event.observe($('frontend_input'), 'change', switchAttributeInputType);
}
//]]>
</script>