<?php
/**
 * @category	Solide Webservices
 * @package		Flexslider
 */
?>
<style>
	.product-param label { padding-right: 10px; }
	.product-param .label { color: black; font-weight: bold; }
	.product-param .label:hover { color: blue; font-weight: bold; }
	.product-param .element { display: none; }
	.product-param input, .product-param select { min-width: 350px; width: auto !important; }
	.product-param-edit .label { display: none; }
	.product-param-edit .element { display: inline; }
	.product-chooser { border: 1px solid #CCC; display: none; margin: 10px 0; padding: 5px; }
</style>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('flexslider')->__('Group Products') ?></h4>
	</div>
	<fieldset id="product_fieldset">
		<div id="messages">
			<ul class="messages">
				<li class="notice-msg">
					<span><?php echo Mage::helper('flexslider')->__('Due to limitations of Magento it\'s only possible to add a slider group to the top or the bottom of a selected product page. Placing a slider on a specific location on a product page will require template customization.') ?></span>
				</li>
			</ul>
		</div>
		<ul>
			<li>
				<span class="product-param">
					<label for="product_sku"><?php echo Mage::helper('flexslider')->__('Show On Product Pages (SKU)') ?></label>
					<a class="label" href="javascript:void(0)"><?php if($this->getIdsString()) { echo $this->getIdsString(); } else { echo Mage::helper('flexslider')->__('Click Here To Add Products'); } ?></a>
					<span class="element">
						<input id="product_sku" class="input-text element-value-changer" type="text" value="<?php echo $this->getIdsString() ?>" name="product_sku">
						<a class="product-chooser-trigger" href="javascript:void(0)">
							<img src="<?php echo Mage::getDesign()->getSkinUrl('images/rule_chooser_trigger.gif') ?>" alt="" class="v-middle product-chooser-trigger" title="<?php echo Mage::helper('flexslider')->__('Open Chooser') ?>" />
						</a>
					</span>
				</span>
				<div class="product-chooser" url="<?php echo Mage::getUrl('adminhtml/promo_widget/chooser/attribute/sku/form/rule_conditions_fieldset', array('_secure' => Mage::app()->getStore()->isAdminUrlSecure())); ?>">
			</li>
		</ul>
	</fieldset>
</div>

<script type="text/javascript">
	var rule_conditions_fieldset = new VarienRulesForm('product_fieldset', '<?php echo Mage::getUrl('/admin/promo_catalog/newConditionHtml/form/rule_conditions_fieldset/', array('_secure' => Mage::app()->getStore()->isAdminUrlSecure())); ?>');
</script>