<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Operation/Contact.php
 */


/**
 * Bronto_Api_Operation_Contact specific Bronto_Api_Operation
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Operation_Contact extends Bronto_Api_Operation
{
    protected $_uniqueKey = array('email', 'mobileNumber');

    /**
     * @see parent
     */
    public function __construct(Bronto_Api $api)
    {
        parent::__construct($api, 'Contact', array(
            'add',
            'update',
            'addOrUpdate',
            'delete',
            'addContactsToWorkflow' => 'add',
            'addContactEvent' => 'add',
            'addToList' => 'add',
            'removeFromList' => 'remove',
            'addToSMSKeyword' => 'add',
            'removeFromSMSKeyword' => 'remove'
        ));
    }

    /**
     * @see parent
     * @return Bronto_Api_Read
     */
    public function createRead(array $readData = array(), array $requestFields = array())
    {
        return parent::createRead($readData, $requestFields)
            ->setRequestFields(array(
                'includeLists' => false,
                'includeSegments' => false,
                'includeSMSKeywords' => false,
                'includeGeoIPData' => false,
                'includeRFMData' => false,
                'includeTechnologyData'  => false,
                'includeEngagementData' => false,
                'fields' => false,
            ));
    }
}
