<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Operation/MailList.php
 */


/**
 * List specific operations
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Operation_MailList extends Bronto_Api_Operation
{
    /**
     * @see parent
     */
    public function __construct(Bronto_Api $api)
    {
        parent::__construct($api, 'List', array(
            'add',
            'update',
            'delete',
            'clear',
        ));
    }

    /**
     * @see parent
     * @param string $method
     * @return boolean
     */
    protected function _supportedPrefix($method)
    {
        if ($method == 'clear') {
            return true;
        } else {
            return parent::_supportedPrefix($method);
        }
    }
}
