<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Operation/Order.php
 */


/**
 * Bronto_Api_Operation_Order specific operation
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Operation_Order extends Bronto_Api_Operation
{
    /**
     * @see parent
     */
    public function __construct(Bronto_Api $api)
    {
        parent::__construct($api, 'Order', array(
            'delete',
            'addOrUpdate'
        ));
        $this->_writeLimit = 10;
    }

    /**
     * Creates a chainable product object
     *
     * @return Bronto_Object
     */
    public function createProduct(array $data = array())
    {
        return new Bronto_Object($data);
    }

    /**
     * @see parent
     * @throws BadMethodCallException
     */
    public function createRead(array $readData = array(), array $requestFields = array())
    {
        throw new BadMethodCallException('The read request is not allowed for Order type.');
    }
}
