<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/functions.php
 */


/**
 * Package level convenience for creating chainable objects
 *
 * @param array $data
 * @return Bronto_Object
 */
function object(array $data = array())
{
    return new Bronto_Object($data);
}

/**
 * Package level convenience for creating API options
 *
 * @param array $data
 * @return Bronto_Api_Options
 */
function options(array $data = array())
{
    return new Bronto_Api_Options($data);
}
