<?php
/**
 * Layered Navigation Pro
 *
 * @category:    AdjustWare
 * @package:     AdjustWare_Nav
 * @version      2.5.4
 * @license:     yc4tx3fdyujjEs5czyndvhoc8zpLrKl3OCuGehtGvM
 * @copyright:   Copyright (c) 2014 AITOC, Inc. (http://www.aitoc.com)
 */
?>
<script type="text/javascript">
    <?php if($this->isHomePage()) :?>
        var lookhomepage = 1;
    <?php else :?>
        var lookhomepage = 0;
    <?php endif;?>
</script>