<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.4.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php 
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
    <?php if (Mage::helper('awautorelated')->checkVersion('1.4')): ?>
        <div id="autorelatedProducts" class="block block-related-product aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>">
            <div class="related">
                <strong><span><?php echo $this->htmlEscape($this->getData('name')) ?></span></strong>
            </div>
            <div class="block-content aw-arp-block-content">
    <?php else: ?>
        <div class="box base-mini mini-related-items aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>">
            <div class="head">
                <h4><?php echo $this->htmlEscape($this->getData('name')) ?></h4>
            </div>
            <div class="content aw-arp-block-content">
    <?php endif; ?>
                <ul>
                    <?php foreach ($collection as $product) : ?>
                        <li class="aw-arp-item">
                            <a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(150) ?>" alt="<?php echo $this->htmlEscape($product->getName()) ?>" width="75" height="75" /></a>
                            <div class="prodGridd">
                            <a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><span class="relatedTitle"><?php echo $this->htmlEscape($product->getName()) ?></span></a><br />
                           <?php //echo $this->getReviewsSummaryHtml($_product, false, true) // DISABLE 
					   
					    $c2c_hide_price =  $product->getResource()->getAttribute('c2c_hide_price')->getFrontend()->getValue($product);
						
					   ?>
                     <?php if($c2c_hide_price == "No") { ?><?php echo $abstractBlock->getPriceHtml($product, true, '-related') ?> <?php }else { ?>
                       <h2 class="spclmsglist"> Ask us about our pricing! </h2>
                     <?php } ?>
                     </div>
                            <?php /*if ($product->isSaleable()) : ?>
                              <div class="aw-arp-addtocart">
                                <p>
                                    <a class="link-cart" href="javascript:setLocation('<?php echo $abstractBlock->getAddToCartUrl($product) ?>');"><?php echo $this->__('Add to Cart') ?></a>
                                </p>
                           </div>
                            <?php else : ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif*/ ?>
                            <?php /*if ($this->helper('wishlist')->isAllow()) : ?>
                                <a href="javascript:setLocation('<?php echo $abstractBlock->getAddToWishlistUrl($product) ?>')" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                            <?php endif;*/ ?>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
                
        <!--<p class="back-top-top">
            <a href="#product-top">Back to top</a>
        </p>-->
                
<?php endif;?>