<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 *
 *
 *
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body id="left-column" <?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?> <?php echo $this->getChildHtml('global_notices') ?> <?php echo $this->getChildHtml('header') ?>
<div class="content-wrapper">
<div class="container_12">
  <div class="main-container col2-left-layout">
    <div class="grid_12"><?php echo $this->getChildHtml('breadcrumbs') ?></div>
    <div class="clear"></div>


     <?php if(Mage::registry('current_product')){ ?>

			<div class="grid_12 col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>

<?php } else { ?>
<!--			--><?php //if(Mage::app()->getFrontController()->getRequest()->getRouteName() != 'cms'){?>
<!--      --><?php //if (Mage::registry('current_category')) { ?>
<!--				<div class="grid_12" style="margin:0px;">-->
<!--					--><?php //echo $this->getLayout()->createBlock('catalog/category_view')->setTemplate('catalog/category/view-header.phtml')->toHtml();?>
<!--				</div>-->
<!--      --><?php //} ?>
<!--      --><?php //} ?>
			<div class="grid_9 col-main">
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div>
			<aside class="grid_3 sidebar sidebar-left">
				<?php echo $this->getChildHtml('left') ?>
            </aside>

<?php } ?>


      <div class="clear"></div>
    </div>
  </div>
</div>
<?php echo $this->getChildHtml('footer') ?> <?php echo $this->getChildHtml('global_cookie_notice') ?> <?php echo $this->getChildHtml('before_body_end') ?> <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>