<?php
$fields_to_fieldsets = $this->getWebform()->getFieldsToFieldsets();
// create field map
$field_map = array();
foreach($fields_to_fieldsets as $fieldset_id => $fieldset){
    foreach($fieldset["fields"] as $field){
        $field_map['fieldset_'.$fieldset_id][]=$field->getId();
    }
}
?>

<script type="text/javascript">
    var logicRules_<?php echo $this->getWebform()->getId()?> = [];
    var targets_<?php echo $this->getWebform()->getId()?> = <?php echo json_encode($this->getWebform()->_getLogicTarget())?>;
    var fieldMap_<?php echo $this->getWebform()->getId()?> = <?php echo json_encode($field_map)?>;
<?php
$logic_rules = $this->getWebform()->getLogic();
foreach ($logic_rules as $logic) {
    if ($logic->getIsActive()) {
?>
    logicRules_<?php echo $this->getWebform()->getId()?>.push({
        'field_id': '<?php echo $logic->getFieldId()?>',
        'action': '<?php echo $logic->getAction()?>',
        'logic_condition': '<?php echo $logic->getLogicCondition()?>',
        'aggregation': '<?php echo $logic->getAggregation()?>',
        'value':<?php echo json_encode($logic->getFrontendValue())?>,
        'target':<?php echo json_encode($logic->getTarget())?>
    });
<?php
    }
}
?>
    // execute form logic
    JSWebFormsLogic(targets_<?php echo $this->getWebform()->getId()?>, logicRules_<?php echo $this->getWebform()->getId()?>);
</script>
