<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Write/Flusher.php
 */

/**
 * OO style flusher observer
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
interface Bronto_Api_Write_Flusher
{
    /**
     * Gets called whenever the write request hit a limit
     * and must now handle the current items to be written.
     *
     * @param Bronto_Api_Write_Pager $iterator
     * @return void
     */
    public function onFlush($iterator);
}
