<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Write/Overflow.php
 */

/**
 * A write overflow exception occuring with a write request
 * hits the write limit without an assigned Bronto_Api_Write_Flusher.
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Write_Overflow extends OverflowException
{
    private $_arguments;

    /**
     * @see parent
     *
     * @param string $message
     * @param array $arguments
     */
    public function __construct($message, $arguments)
    {
        parent::__construct($message, 0, null);
        $this->_arguments = $arguments;
    }

    /**
     * Gets the arguments that were going to be set be the write.
     *
     * @return array
     */
    public function getArguments()
    {
        return $this->_arguments;
    }
}
