<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Model/Delivery.php
 */

/**
 * Model class for delivery level convenience methods
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Model_Delivery extends Bronto_Api_Model_DeliveryAbstract
{
    const TYPE_TRANSACTIONAL = 'transactional';
    const TYPE_TRIGGERED = 'triggered';
    const TYPE_NORMAL = 'normal';
    const TYPE_TEST = 'test';
    const TYPE_FTAF = 'ftaf';
    const TYPE_AUTOMATED = 'automated';
    const TYPE_SPLIT = 'split';

    const STATUS_SENT = 'sent';
    const STATUS_SENDING = 'sending';
    const STATUS_UNSENT = 'unsent';
    const STATUS_ARCHIVED = 'archived';
    const STATUS_SKIPPED = 'skipped';
    const STATUS_TMP = 'tmp';

    /**
     * @see parent
     */
    public function __construct(array $data = array())
    {
        parent::__construct('Delivery', $data);
    }

    /**
     * @see parent
     */
    public function isTransactional()
    {
        return $this->hasType() && $this->getType() == self::TYPE_TRANSACTIONAL;
    }
}
