<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Model/Order.php
 */

class Bronto_Api_Model_Order extends Bronto_Api_Object
{
    /**
     * @see parent
     */
    public function __construct(array $data = array())
    {
        parent::__construct('Order', $data);
    }

    /**
     * Convenience method for adding additional products to
     * the order
     *
     * @return Bronto_Object
     */
    public function addProduct($product)
    {
        if ($product instanceof Bronto_Object) {
            $product = $product->toArray();
        }
        if (!array_key_exists('products', $this->_data)) {
            $this->_data['products'] = array();
        }
        $this->_data['products'][] = $product;
        return $this;
    }
}
