<?php if(Mage::getSingleton('cms/page')->getIdentifier() !== 'email_registration') : ?>
    <div class="container_12">
        <div class="grid_12">
            <div class="mo-12-wrapper grey newsletter-wrapper">
                <div class="border-white">
                    <div class="grid_8">
                        <h1><span>Never</span><span><span> miss out on a deal</span></span></h1>
                    </div>
                    <a style="color:white;" href="<?php echo Mage::getUrl("email_registration")?>">
                        <div class="grid_4 home-box banner-button-solid">Click here to sign up!</div>
                    </a>
                    <div class="grid_12" style="clear:both;">   <h5><span>Be the first to receive updates on new arrivals, promotions, and special events</span></h5></div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>


<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
 $footer_status = $meigee_blacknwhite_general['footer']['footer_status'];
 $footer_static = $meigee_blacknwhite_general['footer']['footer_static'];
?>

<footer id="footer"<?php if ($footer_status == 0): ?> class="default-footer"<?php endif; ?>>
    <?php if ($footer_status == 1): ?>
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalog_footer')->toHtml() ?>
    <?php else: ?>
        <div class="footer-bottom-wrapper">
            <div class="container_12">
                <div class="grid_12">
                    <address><?php echo $this->getCopyright(); ?></address>
                    <?php echo $this->getChildHtml('store_switcher'); ?>
                    <div class="footer-links">
                        <?php echo $this->getChildHtml('cms_footer_links') ?>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    <?php endif; ?>
</footer>
<!--<div class="footer-checkout" style="display:none">-->
<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/footer-checkout.phtml')->toHtml(); ?>
<!--</div>-->
