<div class="container_12">
    <div class="grid_12">

            <div class="mo-12-wrapper grey newsletter-wrapper">
                <div class="border-white">
    <div class="grid_8">
                    <h1><span>Never</span><span><span> miss out on a deal</span></span></h1>

    </div>
                    <div class="grid_4 home-box">
                    <form action="http://cl.exct.net/subscribe.aspx" enctype="application/x-www-form-urlencoded" method="post"><input name="thx" type="hidden" value="http://watsons.com/subscription-successful" /> <input name="err" type="hidden" value="http://watsons.com/error-subscription" /> <input name="SubAction" type="hidden" value="sub_add_update" /> <input name="MID" type="hidden" value="7000752" />
                        <table border="0" cellspacing="0" cellpadding="0" align="center">
                            <tbody>
                            <tr>
                                <td style="width:100%;"><input style="padding-left:10px;" class="sub-input-box" name="Email Address" type="text" placeholder="enter email address..." /></td>
                                <td><input class="sub-submit banner-button-solid" type="submit" value="Submit"/></td>
                            </tr>
                            </tbody>
                        </table>
                    </form>
                    </div>
                    <div class="grid_12" style="clear:both;">   <h5><span>Be the first to receive updates on new arrivals, promotions, and special events</span></h5></div>

                </div>
            </div>

        </div>
    </div>



<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
 $meigee_blacknwhite_general = MAGE::helper('ThemeOptionsBlacknwhite')->getThemeOptionsBlacknwhite('meigee_blacknwhite_general');
 $footer_status = $meigee_blacknwhite_general['footer']['footer_status'];
 $footer_static = $meigee_blacknwhite_general['footer']['footer_static'];
?>

<footer id="footer"<?php if ($footer_status == 0): ?> class="default-footer"<?php endif; ?>>
	<?php if ($footer_status == 1): ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalog_footer')->toHtml() ?>
	<?php else: ?>
		<div class="footer-bottom-wrapper">
			<div class="container_12">
				<div class="grid_12">
					<address><?php echo $this->getCopyright(); ?></address>
					<?php echo $this->getChildHtml('store_switcher'); ?>
					<div class="footer-links">
						<?php echo $this->getChildHtml('cms_footer_links') ?>
                    </div>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	<?php endif; ?>
</footer>
<!--<div class="footer-checkout" style="display:none">-->
<?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/footer-checkout.phtml')->toHtml(); ?>
<!--</div>-->
