<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Object.php
 */

/**
 * The API Bronto_Api_Object represent data returned by the API
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Object extends Bronto_Object
{
    protected $_rawType;

    /**
     * @see parent
     *
     * @param string $rawType
     * @param array $data
     */
    public function __construct($rawType, array $data = array())
    {
        parent::__construct($data);
        $this->_rawType = $rawType;
    }

    /**
     * The transfer type of the API object
     *
     * @return string
     */
    public function getTransferType()
    {
        return $this->_rawType;
    }
}
