<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Serialize/Json/Standard.php
 */


/**
 * Bronto_Serialize_Json_Standard PCL bidirectional serializer
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Serialize_Json_Standard implements Bronto_Serialize_BiDirectional
{
    private static $_enumToMsg = array(
        JSON_ERROR_DEPTH => 'Maximum stack depth exceeded',
        JSON_ERROR_STATE_MISMATCH => 'Underflow or the modes mismatch',
        JSON_ERROR_CTRL_CHAR => 'Unexpected control character found',
        JSON_ERROR_SYNTAX => 'Syntax error, malformed JSON',
        JSON_ERROR_UTF8 => 'Malformed UTF-8 characters',
    );

    /**
     * Reads the last json error for parsing or encoding and throws
     * an exception containing the input.
     *
     * @param mixed $thingOrInput
     * @param boolean $encoding
     * @throws Bronto_Serialize_Exception
     */
    protected function _catchAndThrowError($thingOrInput, $encoding)
    {
        $erroNo = json_last_error();
        if ($erroNo) {
            $error = 'Unknown error';
            if (array_key_exists($erroNo, self::$_enumToMsg)) {
                $error = self::$_enumToMsg[$erroNo];
                throw new Bronto_Serialize_Exception($error, $erroNo, $thingOrInput, $encoding);
            }
        }
    }

    /**
     * @see parent
     */
    public function getMimeType()
    {
        return 'application/json';
    }

    /**
     * @see parent
     */
    public function encode($thing)
    {
        $return = json_encode($thing);
        $this->_catchAndThrowError($thing, true);
        return $return;
    }

    /**
     * @see parent
     */
    public function decode($input)
    {
        $return = json_decode($input, true);
        $this->_catchAndThrowError($input, false);
        return $return;
    }
}
