<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Transfer/Exception.php
 */

/**
 * Transfer related exceptions. May or may not
 * contain information about the request
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Transfer_Exception extends RuntimeException
{
    private $_request;

    /**
     * @see parent
     */
    public function __construct($message, $code, $request)
    {
        parent::__construct($message, $code);
        $this->_request = $request;
    }

    /**
     * @return Bronto_Transfer_Request
     */
    public function getRequest()
    {
        return $this->_request;
    }
}
