<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Transfer/Request.php
 */

/**
 * Interface that defines a transferable request entity
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
interface Bronto_Transfer_Request
{
    const GET = 'GET';
    const POST = 'POST';
    const PUT = 'PUT';
    const DELETE = 'DELETE';

    /**
     * Add/set a new transfer header
     *
     * @param string $name
     * @param mixed $value
     * @return Bronto_Transfer_Request
     */
    public function header($name, $value);

    /**
     * Add/set a new transfer POST param
     *
     * @param string $name
     * @param mixed $value
     * @return Bronto_Transfer_Request
     */
    public function param($name, $value);

    /**
     * Add/set a new transfer query parameter
     *
     * @param string $name
     * @param mixed $value
     * @return Bronto_Transfer_Request
     */
    public function query($name, $value);

    /**
     * Some raw data to send
     *
     * @param string $data
     */
    public function body($data);

    /**
     * Completes the built request and returns a
     * Bronto_Transfer_Response entity to interact with
     *
     * @return Bronto_Transfer_Response
     */
    public function respond();
}
