<?php $posts = $this->getPosts(); ?>
<header class="page-title category-title">
    <h2><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h2>
</header>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <header class="postTitle page-title category-title">
            <h3><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h3>
        </header>
        <div class="postDetails">
            <?php if ($this->getCommentsEnabled()): ?>
                <?php echo $post->getCommentCount(); ?> 
                <a href="<?php echo $post->getAddress(); ?>#commentBox" >Comments</a>&nbsp;&nbsp;|&nbsp;&nbsp;
            <?php endif; ?>
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <?php echo Mage::helper('blog')->__('Posted in'); ?>
                <?php foreach ($postCats as $data): ?>
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a>
                <?php endforeach; ?>
            <?php else: ?>
                <?php echo Mage::helper('blog')->__('Posted'); ?>
            <?php endif; ?>&nbsp;&nbsp;|&nbsp;&nbsp;<?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?>
        </div>
        <div class="post-date"><?php echo $post->getCreatedTime(); ?></div>
        <div class="clear"></div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>
        <?php echo $this->getBookmarkHtml($post) ?>
    </div>
<?php endforeach; ?>
<?php echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
