<?php    
/*------------------------------------------------------------------------
 # Smartaddons Mega Products  - Version 1.0
 # Copyright (C) 2010-2011 The YouTech Company. All Rights Reserved.
 # @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 # Author: The YouTech Company
 # Websites: http://www.smartaddons.com
 -------------------------------------------------------------------------*/
?>

<?php if(!empty($items)){?>
    <div id="yt-mega-news" class="yt_mega_news">	
        <div id="ytc_tabs" class="theme2"> 
             <?php    
           //var_dump($items); die;
               if(!empty($items)){$ij=1;	$counttotal = count($items);  
                foreach ($items as $key=>$value) {                        
			
			if ($ij==1) {
			?>		 
			<div style="width:<?php echo $options->module_width;?>px; float: left; padding-bottom:10px"> <?php }?>
			<div class="box" style="width:<?php echo ($width_category-1);?>%; float: left;"> 	
				<div class="tabs" >			   
				<div class="category_title_left">&nbsp;</div>
				<div class="category_title_center">
				<div class="category_name">
					<?php if ( $sub_category_link==1 ) { ?>
							<a href="<?php echo ($value->url);?>" <?php echo $target;?>>
							<?php echo strtoupper($value->title); ?>
							</a>
					<?php } else{
							echo strtoupper($value->title);
					}?>
				</div>
				</div> 
				<div class="category_title_right">&nbsp;&nbsp;&nbsp; </div>
			   </div> <!--end tabs-->
			
                <div class="box-wrapper">
                <?php 
                 $j=1;                   
                 $firstVal = current($value->child);
                ?>
                    <div class="content-box <?php if($j==1) echo "current";?>">
                        <div class="content">
						<div class="col-one col">							
                            <?php if($show_title ==1){?>
							<?php 	if ($product_title_linkable==1) { ?>
										<a href="<?php echo $firstVal->url;?>" <?php echo $target;?>>
										<?php echo $firstVal->title;?> 
										</a>
                            <?php 	} else {
										echo $firstVal->title; 
									}
								}
							?>
						</div>
						<?php if ($options->product_price_disp ==1 ) { ?>
							<div class="megaproducts_price">
								<?php echo $firstVal->price_html; ?>
							</div>
						<?php } ?>
						<?php if ($options->product_reviews_disp ==1 ) { ?>
							<div class="megaproducts_reviews">
								<?php echo $firstVal->review_html;?>
							</div>
						<?php } ?>
						<?php if ($options->product_stock_disp ==1 ) { ?>
							<div class="megaproducts_stock">
								<?php echo $firstVal->stock_html;?>
							</div>
						<?php } ?>
						<div class="col-two col">
                        <?php if (($show_image == 1) && ($firstVal->image!='')){ ?>
                            <div class="image"> 
							<?php                                        
							
							 if($link_image ==1) {?>
							
							<a href="<?php echo $firstVal->url;?>" <?php echo $target;?>>
							<img src="<?php echo $firstVal->image;?>" /><br>
							</a>
							
							<?php  } 
							else 
							{?>
							<img src="<?php echo $firstVal->image?>"/>
							<?php } ?>
							</div>
							<?php } ?>
							<div class="sub_content">
								<p style="line-height: 1.5;"><?php if ($show_description == 1) {
										 echo $firstVal->description; }?></p>
								<?php if ($show_read_more_link == 1) {?>   
							   <div class="read_more"> <a href="<?php echo $firstVal->url;?>" <?php echo $target;?>><?php echo $read_more_text;?></a></div>
                            <?php }?>
                            </div>
					    </div>
					</div>
						
                    <div class="col-three col">
                            <ul class="link"> <?php $i=1; foreach($value->child as $key1=>$value1){if($i!=1){?>
                                <li>
								<div class="arrow">&nbsp;&nbsp;</div>
								<a href="<?php echo $value1->url?>" <?php echo $target; ?>><?php echo $value1->title?></a></li>
                                 <?php };$i++;}?>                            
                            </ul>
					 	 
					
					<ul class="link_category"> <?php if ($show_all_articles ==1) { ?>
					<li>
					<div class="arrow1"> &nbsp;</div> 
					<a href="<?php echo ($value->url);?>" <?php echo $target;?>>
					<?php echo $view_all;?></a></li>
				    <?php }?>                      
                    </ul>	
					</div>		
                    </div>   <!-- END content-box -->
							
				 </div> <!-- END Box Wrapper -->
			     </div> <!-- END box -->
				 <?php if(($counttotal) == $ij){?>
                        </div><?php } else {?>
                        <?php if($ij% $numcols==0) {?> </div><div style="width:<?php echo $options->module_width;?>px;  float: left;"><?php }?>
                        <?php }?>                             
                        <?php $j++; $ij++;}} ?>                                      
                               
										</div>
    </div>   
  <?php  } else { echo $this->__('Has no content to show!');}?>