<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Functional/None.php
 */

/**
 * The Bronto_Functional_None type represents a "Nothing" container
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Functional_None extends Bronto_Functional_Option
{
    /**
     * @return boolean
     */
    public function isDefined()
    {
        return false;
    }

    /**
     * @throws BadMethodCallException
     */
    public function get()
    {
        throw new BadMethodCallException('None->get() cannot not be invoked.');
    }
}
