<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Functional/Some.php
 */

/**
 * The Bronto_Functional_Some type contains some kind of value
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Functional_Some extends Bronto_Functional_Option
{
    private $_id;

    /**
     * Create the some with a contained value
     *
     * @param mixed $identity
     */
    public function __construct($identity)
    {
        $this->_id = $identity;
    }

    /**
     * @return boolean
     */
    public function isDefined()
    {
        return true;
    }

    /**
     * @return mixed
     */
    public function get()
    {
        return $this->_id;
    }
}
