<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Strategy/Error.php
 */


/**
 * OO style error recover strategy
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
interface Bronto_Api_Strategy_Error
{
    /**
     * Gets called whenever the Bronto_Api client encounters an
     * Bronto_Api_Exception. This recover returns whether or not it
     * can recover by attempting the same request.
     *
     * @param Bronto_Api_Exception $e
     * @param Bronto_Api $api
     * @param Bronto_Object $request
     * @return boolean
     */
    public function recover(Bronto_Api_Exception $e, Bronto_Api $api, Bronto_Object $request);
}
