<div class="page-head">
    <h3><?php echo Mage::helper('testimonial')->__('Write Your Own Testimonial') ?></h3>
</div>
<?php
$data_form = Mage::getSingleton('core/session')->getFormData(); 
?>
<form action="<?php echo $this->getAction() ?>" id="testimonial-form" method="post" enctype="multipart/form-data" onsubmit="return jcap();" name="testimonial-form" >
<fieldset>

<div class="div_submit">
			<div class="div_submit_content" >

        <?php // do not remove div - some problem whith validator in IE ?>
        <div class="form-list">
        <label for="client_name" class="required"><?php echo Mage::helper('testimonial')->__('Your Name') ?><em>*</em></label><br />
        <input class="required-entry input-text" name="client_name" id="client_name" style="width: 450px;" type="text" value="<?php if($data_form !=null) echo $data_form->getClientName();?>" />
        </div>
	
        <div class="form-list">
        <label for="email" class="required"><?php echo Mage::helper('testimonial')->__('Your Email') ?><em>*</em></label><br />
        <input name="email" type="text" id="email" style="width: 450px;" class="required-entry validate-email input-text" value="<?php if($data_form !=null)  echo $data_form->getEmail();?>" />
        </div>
     	
        <div>
        <label for="company"><?php echo Mage::helper('testimonial')->__('Your Company') ?></label><br />
        <input name="company" class="input-text" id="company" style="width: 450px;" type="text" value="<?php if($data_form !=null)  echo $data_form->getCompany();?>" />
        </div>
        
		<!-- v2.2.2 - added class="input-text" - phamthuy -->
		<div>
        <label for="address"><?php echo Mage::helper('testimonial')->__('Your Address') ?></label><br />
        <input name="address" class="input-text" type="text" id="address" style="width: 450px;" value="<?php if($data_form !=null) echo $data_form->getAddress();?>"  />
        </div>
        
        <div style="padding:5px 0px;">
        <label for="media"><?php echo Mage::helper('testimonial')->__('Upload Media(Video, Image):') ?></label>
        <input class="MW_validate_media1" type="file" name="media1" id="media1" style="width:200px;margin-left:20px;" />
        </div>
        
        <div>
        	<label for="media_url"><?php echo Mage::helper('testimonial')->__('Media(Video, Image) URL') ?></label><br />
       		 <input class="MW_validate_media input-text" name="media_url" type="text" id="media_url" style="width: 450px;"  value="<?php if($data_form !=null)  echo $data_form->getMediaUrl();?>" />
        </div>

        <div class="form-list">
        <label for="description" class="required"><?php echo Mage::helper('testimonial')->__('Your Testimonial') ?><em>*</em></label><br />
        <textarea class="required-entry" name="description" id="description" cols="53" rows="10" style="width: 450px;"><?php if($data_form !=null)  echo $data_form->getDescription();?></textarea>
        </div>
       
		<?php if (Mage::getStoreConfig("hm_testimonial/general/enable")==true): ?>
		 <div class="form-list">
		<label for="security_code" class="required"><?php echo Mage::helper('testimonial')->__('Security code') ?><em>*</em></label><br />
		
			<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'testimonial/md5.js';?>"></script>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS).'testimonial/jcap.js';?>"></script>

				<script type="text/javascript">
				sjcap();
				</script>
				<noscript><p>[This resource requires a Javascript enabled browser.]</p></noscript>
		</div>
	<?php endif;?>
	<br/>
   <div class="button-set">        
        <button class="form-button button right"  id="submit" name="submit" type="submit"><span><?php echo Mage::helper('testimonial')->__('Submit Testimonial') ?></span></button>
    </div>
    </div>
     </div>
</fieldset>
<!--<p><input type="submit" id="submit" name="submit" value="Submit"></p>-->

</form>
	<script type="text/javascript">
	editForm = new Validation('testimonial-form'); 
	</script>
