<tr>
    <td colspan="4">
        <div id="bronto_permissionchecker_results" class="grid">
            <ul class="messages">
                <li class="notice-msg">
                    <ul>
                        <li>
                            <span>
                                Press the 'Check Permissions' button to check your settings.
                            </span>
                        </li>
                        <li>
                            <span>
                                Please note this could take a while depending on your
                                hardware and file system size
                            </span>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </td>
</tr>