<?php
$channel_path = Mage::getBaseUrl('media').'jobs/';

$appId = Mage::getStoreConfig('jobs/fbsettings/appid');
$appsecret = Mage::getStoreConfig('jobs/fbsettings/secret');


?>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<?php echo $appId; ?>', // App ID
      channelUrl : '<?php echo $channel_path; ?>channel.php', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
    FB.Event.subscribe('auth.login', function(response) {
    // do something with response
    $j('#fb_message_section').css('display','block');
    });

  };


  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<?php echo $appId; ?>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));



</script>

<?php
$base_url = Mage::getBaseDir('media').DS.'jobs'.DS;
require_once ($base_url.'src'.DS.'facebook.php');

$facebook = new Facebook(array(
  'appId'  => $appId,
  'secret' => $appsecret,
));

$redirect_url =  $this->helper('core/url')->getCurrentUrl();

// Get User ID
$user = $facebook->getUser();
if (!$user) {
//    $loginUrl = $facebook->getLoginUrl($params);
    $loginUrl   = $facebook->getLoginUrl(
            array(
                'scope'         => 'publish_stream',
                'redirect_uri'  => $redirect_url
            )
    );
}
else {
    $logoutUrl = $facebook->getLogoutUrl();
}









$id = $this->getRequest()->getParam('id');


?>
 
    


    
<?php

$base = Mage::getBaseUrl();




$randomids = array();


?>
<script type="text/javascript">
var $j = jQuery.noConflict();

var fb_loggedin = <?php if($user) echo 'true'; else echo 'false'; ?>;


$j(document).ready(function(){
    
$j(".tab-item-link-x").bind("click", tabclicked);

$j("#x-homeslider").attr("style", "");
$j("#x-slider").attr("style", "display:none;");
$j("#x-nav").attr("style", "display:none;");


   
   $j('#colorsample').css("background-color", $j('#textcolor').val());
   $j('#sampletimerStrokeColor1').css("background-color", $j('#timerStrokeColor1').val());
   $j('#sampletimerStrokeColor2').css("background-color", $j('#timerStrokeColor2').val());
   $j('#samplecaptionBackgroundColor').css("background-color", $j('#captionBackgroundColor').val());


     $j('#tweet_text').keyup(function() {
        var value = $j(this).val();
        var vlength=value.length;
        if(140-vlength<0){
        value= value.substring(0, 140);
        $j(this).val(value);
        }
        value = $j(this).val();
        vlength=value.length;
        $j(".shortcharleft").html(140-vlength);
        });




});




function tabclicked(){
    var tab_id = $j(this).attr("id");
    
    $j(".tab-item-link-x").removeClass("active");
    $j(this).addClass("active");
    
    if(tab_id == "xselect_slider_tab_5")
    {
        $j("#x-homeslider").attr("style", "");
        $j("#x-slider").attr("style", "display:none;");
        $j("#x-nav").attr("style", "display:none;");
        
    }
    if(tab_id == "xselect_slider_tab_1")
    {
        $j("#x-homeslider").attr("style", "display:none;");
        $j("#x-slider").attr("style", "");
        $j("#x-nav").attr("style", "display:none;");
        
    }
    if(tab_id == "xselect_slider_tab_2")
    {
        $j("#x-homeslider").attr("style", "display:none;");
        $j("#x-slider").attr("style", "display:none;");
        $j("#x-nav").attr("style", "");
    }

}


function publishtofb()
{
    
    fbmsg = jQuery('#wall_message').val();
    
    fbposturl = "<?php echo Mage::getUrl('jobs/fbconnect/post'); ?>"
    jobId = "<?php echo $id; ?>";
    //fbposturl = temp_fbposturl.replace("index.php/", "");
    
    
    str = "fbmsg="+fbmsg+"&jobid="+jobId;

    jQuery.ajax({
            type: "POST",
            url: fbposturl,
            data: str,
            dataType: "json",
            complete : function(data) {
                alert(data.responseText);
                

            }
            
            });
}


function tweetit()
{
    
    twmsg = jQuery('#tweet_text').val();
    
    twposturl = "<?php echo Mage::getUrl('jobs/fbconnect/tweet'); ?>"
    jobId = "<?php echo $id; ?>";
    //fbposturl = temp_fbposturl.replace("index.php/", "");
    
    
    str = "twmsg="+twmsg+"&jobid="+jobId;

    jQuery.ajax({
            type: "POST",
            url: twposturl,
            data: str,
            dataType: "json",
            complete : function(data) {
                if(data.responseText == "200")
                {
                    alert("Message was successfully posted.");
                }
            else {
                alert("Something went wrong, please try again.");
            }
                

            }
            
            });
}

</script>

<ul class="tabs-horiz" id="category_info_tabs">
    <li>
        <a class="tab-item-link-x active" title="Facebook" id="xselect_slider_tab_5" href="javascript:void(0);">
            <span>Facebook</span>
        </a>
        
    </li>
    <li>
        <a class="tab-item-link-x" title="LinkedIn" id="xselect_slider_tab_1" href="javascript:void(0);">
            <span>LinkedIn</span>
        </a>
        
    </li>
    <li>
        <a class="tab-item-link-x" title="Twitter" id="xselect_slider_tab_2" href="javascript:void(0);">
            <span>Twitter</span>
        </a>
        
    </li>

</ul>



<div id="tab-content">    
    
<?php //++++++++++++++++++++++Facebook TAB+++++++++++++++++++++ ?> 
    <div id="x-homeslider">
        <div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">Facebook</h4>
        <div class="form-buttons"></div>
    </div>
    <div id="xselect_form" class="fieldset ">
        <div id="my-hor-scroll">
        <?php if(isset($id) && $id!=''){ ?>    
           
            <div class="hor-scroll">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="addlider">Facebook Connect</label></td>
                            <td class="value"><?php if(!$user){ ?>
                                
                                <a href="<?php echo $loginUrl; ?>"><button style=""  class="scalable save" type="button" ><span>Login</span></button></a>
                                <!--<div class="fb-login-button" data-show-faces="true" data-width="200" data-max-rows="1"></div>-->
                                <?php }else { ?>
                                <a href="<?php echo $logoutUrl; ?>"><button style=""  class="scalable save" type="button" ><span>Logout</span></button></a>
                                <?php } ?>
                            </td>
                            
                                
                        </tr>
                            
                        
                    </tbody>
                </table>  
            </div>  
            
            <div id="fb_message_section" <?php if(!$user){ ?>style="display:none"<?php } ?>>
                <div class="hor-scroll">
                    <form action="<? echo Mage::getUrl('jobs/fbconnect/post');?>" method="post">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="wall_message">Message</label></td>
                            <td class="value">
                                <textarea name="wall_message" id="wall_message"></textarea>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <button style="" onClick="publishtofb();" class="scalable save" type="button" ><span>Publish to Wall</span></button>
                            </td>
                        </tr>
                            
                        
                    </tbody>
                </table>  
                </form>
            </div> 
            </div>
            
            <?php }else { ?>
                 <div class="hor-scroll">
                     <p>
                         Please save the job first to post it to facebook wall.
                     </p>
            </div> 
            
            <?php } ?>
        </div>
        
        
        
    
</div>
    
</div>    

        
    </div>
    
<?php //++++++++++++++++++++++LinkedIn TAB++++++++++++++++++++++++++ ?> 
        <div id="x-slider">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">LinkedIn</h4>
                    <div class="form-buttons"></div>
                </div>
                <div id="xselect_form" class="fieldset ">
                <div class="hor-scroll">
                
                    <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
                    <script type="IN/Share" data-counter="top"></script>

                </div>
                      
                </div>
            </div>
        </div>
<?php //++++++++++++++++++++++Twitter TAB++++++++++++++++++++++++++ ?>    
        <div id="x-nav">
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-edit-form fieldset-legend">Twitter</h4>
                    <div class="form-buttons"></div>
                </div>
                <div id="xselect_form" class="fieldset ">
                
  
           

            
                <div class="hor-scroll">
                    <form action="<? echo Mage::getUrl('jobs/fbconnect/tweet');?>" method="post">
                <table cellspacing="0" class="form-list">
                    <tbody>
                        <tr>
                            <td class="label"><label for="wall_message">Message</label></td>
                            <td class="value">
                                <textarea name="tweet_text" id="tweet_text"></textarea>
                                <p class="note"><span class="deschint">Max 140 characters, remaining: </span><span class="shortcharleft">140</span></p>
                            </td>
                        </tr>
                        
                        <tr>
                            <td class="label"></td>
                            <td class="value">
                                <button style="" onClick="tweetit();" class="scalable save" type="button" ><span>Tweet</span></button>
                            </td>
                        </tr>
                            
                        
                    </tbody>
                </table>  
                </form>
            </div> 

                      
                </div>
            </div>
        </div>

</div>
    

