<?php    
/*------------------------------------------------------------------------
 # Smartaddons Mega Products  - Version 1.0
 # Copyright (C) 2010-2011 The YouTech Company. All Rights Reserved.
 # @license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
 # Author: The YouTech Company
 # Websites: http://www.smartaddons.com
 -------------------------------------------------------------------------*/
?>
<?php if(!empty($items)){?>
    <div id="yt-mega-news" class="yt_mega_news">	
        <div id="ytc_tabs" class="theme3">
            <?php    
				if(!empty($items)){
					$i=1;	
					$counttotal = count($items);   		   
					foreach ($items as $key=>$value) {
			
						if ($i==1) {
			?>		 
							<div style="width:<?php echo $width_module;?>%; float: left;">
			<?php 		}?>
				
						<div class="box" style="width:<?php echo ($width_category);?>%;"> 	
			
							<div class="tabs" >			   
								<div class="category_title_left">&nbsp;</div>
								<div class="category_title_center">
									<div class="category_name">
									<?php if ( $sub_category_link == 1) { ?>
										<a href="<?php echo ($value->url);?>" <?php echo $target;?>>
											<?php echo strtoupper($value->title); ?>
										</a>
									<?php } else {
											echo strtoupper($value->title);
										}
									?>
									</div>
								</div> 
								<div class="category_title_right">&nbsp;&nbsp;&nbsp; </div>
							</div> <!--end tabs-->
				 
							<div class="box-wrapper">   
								<?php 
								$j=1;  
								?> 
									<div class="content-box <?php if($j==1) echo "current";?>">
									<?php 	
									$ij=1;	
									$counttotal_item = count($value->child);   
													
									foreach ($value->child as $key1=>$value1) {
										if($ij==1){?> 					 
											<div class="normal-content" style="width: <?php echo $width_normal_content;?>%;">
										<?php }?>					 
										<div class="content" style="width: <?php echo ($width_item);?>%">
											<div class="sub-content" style="overflow: hidden; ">	
												<div class="col-one col">							
													<?php if($show_title ==1){?>
													<?php if ($product_title_linkable == 1) { ?>
														<a href="<?php echo $value1->url;?>" <?php echo $target;?>>
															<?php echo $value1->title;?> 
														</a>
													<?php } else {
																echo $value1->title;
															}
														}
													?>                     
												</div>	
												<?php if ($options->product_price_disp ==1 ) { ?>
													<!--[if IE 7]>
														<br>
													<![endif]-->
													<div class="megaproducts_price" >
														<?php echo $value1->price_html; ?>
													</div>
												<?php } ?>
												<?php if ($options->product_reviews_disp ==1 ) { ?>
													<div class="megaproducts_reviews">
														<?php echo $value1->review_html;?>
													</div>
												<?php } ?>
												<?php if ($options->product_stock_disp ==1 ) { ?>
													<div class="megaproducts_stock">
														<?php echo $value1->stock_html;?>
													</div>
												<?php } ?>
												<div class="col-two col">
													<?php if (($show_image == 1)&& ($value1->image!='')){ ?>
													<div class="image">
																<?php                                        
													
														if($link_image ==1) {?>
														
															<a href="<?php echo $value1->url;?>" <?php echo $target;?>>
															<img src="<?php echo $value1->image;?>" /><br>
															</a>
														
														<?php  } 
														else 
														{?>
															<img src="<?php echo $value1->image;?>"/>
														<?php } ?>
													</div>
														<?php } ?>
													<div class="sub_content" style="line-height: 1.5;">							
														<?php if (($show_description == 1) && ($value1->description!='')) {?>
														<div class="article_desc" style="line-height: 1.5;">
														<?php echo $value1->description;?>
														</div>
														<?php }?>
														<?php if (($show_read_more_link == 1) && ($value1->description!='')) {?>   
														<div class="read_more"> 
														<a href="<?php echo $value1->url;?>" <?php echo $target;?>><?php echo $read_more_text;?>
														</a>
														</div>
														<?php }?>
													</div>
												</div> 
											</div><!--end sub-content-->
										</div>		<!-- END content -->			
											<?php if(($counttotal_item) == $ij){?>
											</div><?php } else {?>
											<?php if($ij%$num_items==0) {?> </div><div class="normal-content"> <?php }?>
											<?php }?>                             
											<?php $ij++;
									} ?>          
									
									<ul class="link_category"> <?php if ($show_all_articles ==1) { ?>
									<li>
									<div class="arrow1"> &nbsp;</div>     
									<a href="<?php echo ($value->url);?>" <?php echo $target;?>><?php echo $view_all;?></a></li>
												
									<?php }?>                      
									</ul>	
									</div>
												 
								
							</div> <!-- END box-wrapper -->	 
						</div> <!-- END box -->
			<?php 		if(($counttotal) == $i){?>
							</div>
			<?php 		} else {?>
            <?php 			if($i% $numcols==0) {?>
								</div>
								<div style="width:<?php echo $width_module;?>%; float: left;">
			<?php 			}?>
            <?php 		}?>                             
            <?php 		$j++; 
						$i++;
					}
				} ?>                                    
                         
		</div>
    </div>   
  <?php } else { echo $this->__('Has no content to show!');}?>