<div style="padding:6px; margin-bottom:10px; background-color:#eee; border:1px solid #dedede">See <?php echo $this->getConfigLink() ?> for additional configuration </td></div>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
            <td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
