<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Logger/LogCollection.php
 */

/**
 * A log collection contains multiple appenders to write
 * a single log message across multiple outputs.
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Logger_LogCollection extends Bronto_Logger_LogAbstract implements IteratorAggregate
{
    protected $_handlers = array();

    /**
     * Construct a collection with a target level and handlers
     *
     * @param int $targetLevel
     * @param boolean $backtrace
     * @param array $handlers
     */
    public function __construct($targetLevel = Bronto_Logger_LogInterface::INFO, $backtrace = true, $handlers = array())
    {
        parent::__construct($targetLevel, $backtrace);
        $this->_handlers = $handlers;
    }

    /**
     * @see parent
     */
    public function getIterator()
    {
        return new ArrayIterator($this->_handlers);
    }

    /**
     * Adds an additional handler to this collection
     *
     * @param Bronto_Logger_LogHandler $handler
     * @return Bronto_Logger_LogCollection
     */
    public function addHandler(Bronto_Logger_LogHandler $handler)
    {
        $this->_handlers[] = $handler;
        return $this;
    }

    /**
     * @see parent
     */
    protected function _log($level, $message, $backtrace)
    {
        foreach ($this as $handler) {
            $handler->write($level, $message, $backtrace);
        }
    }
}
