<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Logger/LogHandler.php
 */

/**
 * A log handler is more or less an appender that writes
 * to a given location with some appender specific
 * implementation (outside of potentially logging).
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
interface Bronto_Logger_LogHandler
{
    /**
     * Writes the message at the given level
     * and an optional backtrace
     *
     * @param int $level
     * @param string $message
     * @param array $backtrace
     */
    public function write($level, $message, $backtrace);
}
