<?php /** @var $this Bronto_Email_Block_Adminhtml_System_Email_Template */ ?>
<div style="padding:6px; margin-bottom:10px; background-color:#eee; border:1px solid #dedede">See <?php echo $this->getConfigLink() ?> for additional configuration </td></div>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-system-email-template"><?php echo $this->getHeaderText() ?></h3></td>
            <td class="form-buttons">
                <?php echo $this->getChildHtml('back_button') ?>
                <?php echo $this->getChildHtml('log_button') ?>
                <?php echo $this->getChildHtml('import_button') ?>
                <?php echo $this->getChildHtml('add_button') ?>                
            </td>
        </tr>
    </table>
</div>
<div>
    <?php echo $this->getChildHtml('grid') ?>
</div>
