<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Read/ByDirection.php
 */

/**
 * Implementing pager that uses the readDirection in reads.
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Read_ByDirection extends Bronto_Api_Read_Pager
{
    const FIRST = 'FIRST';
    const NEXT = 'NEXT';

    /**
     * @see parent
     * @return string
     */
    protected function _getPage($request)
    {
        return $request->safeReadDirection()->getOrElse(self::FIRST);
    }

    /**
     * @see parent
     */
    protected function _nextPage($request)
    {
        $request->withReadDirection(self::NEXT);
    }

    /**
     * @see parent
     */
    protected function _setPage($request, $pageNumber)
    {
        $request->withReadDirection($pageNumber);
    }
}
