<?php
/**
 * This file was generated by the ConvertToLegacy class in bronto-legacy.
 * The purpose of the conversion was to maintain PSR-0 compliance while
 * the main development focuses on modern styles found in PSR-4.
 *
 * For the original:
 * @see src/Bronto/Api/Read/ByPage.php
 */

/**
 * Implementing pager using tradition pageNumber for reads.
 *
 * @author Philip Cali <philip.cali@bronto.com>
 */
class Bronto_Api_Read_ByPage extends Bronto_Api_Read_Pager
{
    /**
     * @see parent
     * @return int
     */
    protected function _getPage($request)
    {
        return $request->getData()->safePageNumber()->getOrElse(1);
    }

    /**
     * @see parent
     */
    protected function _nextPage($request)
    {
        $pageNumber = $this->_getPage($request);
        $pageNumber++;
        $request->getData()->setPageNumber($pageNumber);
    }

    /**
     * @see parent
     */
    protected function _setPage($request, $pageNumber)
    {
        $request->getData()->setPageNumber($pageNumber);
    }
}
