<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<div class="block block-subscribe">
	<div class="block-title">
        <div id="account-signup-form">
            <h3>Sign up Today!<br />
                News &amp; Information</h3>
            Stay Up To Date With The Latest Offers!
            <a title="Join Watsons Newsletter!" href="/subscription"><img style="border: 0 none; vertical-align: middle; display: block; margin-left: auto; margin-right: auto;" title="Watsons Newsletter Signup" src="http://www.watsons.com/media/wysiwyg/watsons-newsletter-join.jpg" alt=""></a></div>
        </div>
        <!--
		<strong>
			<span><?php echo $this->__('Sign Up Today!') ?></span>
		</strong>
	</div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
        <div class="block-content">
            <div class="form-subscribe-header">
                <label for="newsletter"><?php echo $this->__('Stay Up To Date With The Latest Offers!') ?></label>
            </div>
            <div class="input-box">
               <input type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button"><span><span><?php echo $this->__('JOIN NOW FOR FREE') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    //]]>
    </script>
    -->
</div>
